---
#
# Author: Aniruddha Gokhale
# CS4287/5287 Principles of Cloud Computing
# Created: Fall 2024
#
# Purpose: 
#   This playbook can be used if you would like to try doing
#   the actions from the master playbook step by step. Simply
#   copy the next play from the master to here and execute
#   just this play and make sure it is working. If everything
#   works correctly, you may then terminate your VMs once again
#   and just run the master playbook end to end
#


#####################################################
### Play 3: Get facts from Cloud VM
#
# In this play, you must retrieve various facts of the
# VMs you have created. The most important are their
# private IP addresses that you will need in subsequent
# plays
#####################################################
- name: "Play 3: Perform fact gathering on all Cloud VMs"
  hosts: LocalMC  # specified in the Inventory file
  remote_user:  "{{ local_user }}"

  gather_facts: no
  become: false
  collections:
  - ansible-base
  - openstack.cloud.collection

  tasks:    # the task to be performed
  # @@ You have to write the following child playbook @@
  - import_tasks: tasks/playbook_retrieve_facts_vms.yaml

...

