---
# Playbook to create VMs on Chameleon Cloud

- name: "Create the VMs on Chameleon Cloud"
  openstack.cloud.server:
    cloud: "{{ cloud_name }}"
    name: "{{vm_name_prefix}}-{{ item }}"
    state: present
    key_name: "{{ ssh_key_name }}"
    image: "{{ image_name }}"
    flavor: "{{vm_flavor}}"
    network: "{{network_name}}"
    security_groups: default
    wait: yes
    timeout: 200
  loop: "{{ range(1, num_vms + 1) }}"
  register: vm_info

- name: "Output the information of the created VMs"
  debug:
    var: vm_info