---
- name: "Update apt cache"
  apt:
    update_cache: yes

- name: "Install required apt packages"
  apt:
    name: "{{ item }}"
    state: present
  loop:
    - python3
    - python3-pip
    - docker.io